# Site Settings
title                    : "Siavash Shami"
title_separator          : "-"
name                     : "Siavash Shami"
description              : "Personal website of Siavash Shami - Geodesy and InSAR Researcher"
url                      : https://siavashshami.github.io
baseurl                  : ""
repository               : "siavashshami/siavashshami.github.io"
breadcrumbs              : false
future                   : true

# Site Author
author:
  name                   : "Siavash Shami"
  avatar                 : "profile.png"
  bio                    : "M.Sc. in Geodesy | InSAR & Remote Sensing Researcher"
  email                  : "siavashshami@email.kntu.ac.ir"
  cv                     : "https://siavashshami.github.io/files/CV.pdf"
  orcid                  : "https://orcid.org/0000-0002-6369-7170"
  webofscience           : "https://www.webofscience.com/wos/author/record/ABE-9631-2021"
  scopus                 : "http://www.scopus.com/inward/authorDetails.url?authorID=57216342203&partnerID=MN8TOARS"
  googlescholar          : "https://scholar.google.com/citations?hl=en&user=ZBOVn9cAAAAJ&view_op=list_works&authuser=1&sortby=pubdate"
  linkedin               : "siavashshami"
  github                 : "siavashshami"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - LICENSE
  - README
  - node_modules
  - vendor
  - tmp
  - log
encoding                 : "utf-8"
markdown_ext             : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown                 : kramdown
highlighter              : rouge
lsi                      : false
excerpt_separator        : "\n\n"
incremental              : false

# Markdown Processing
kramdown:
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  footnote_nr            : 1
  entity_output          : as_char
  toc_levels             : 1..6
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  code:
    output: true
    permalink: /resources/code/:path/
  software:
    output: true
    permalink: /resources/software/:path/
  data_pages:
    output: true
    permalink: /resources/data/:path/
  tutorials:
    output: true
    permalink: /resources/tutorials/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path              : ""
      type              : pages
    values:
      layout            : single
      author_profile    : true
  # _publications
  - scope:
      path              : ""
      type              : publications
    values:
      layout            : single
      author_profile    : true
      share             : true
      comments          : true

# Sass/SCSS
sass:
  sass_dir               : _sass
  style                  : compressed

# Outputting
permalink                : /:categories/:title/
timezone                 : America/Los_Angeles

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings              : all
  ignore:
    envs                 : development
